#!/usr/bin/env python3
"""Generate the PolyKybd Flasher launcher and notification icons.

The mark is a variant of the host's brand mark (tools/gen_brand_icons.py): the
same 6x6 keycap grid, key shape, blue -> cyan sweep and dark body. The host and
forwarder spell P and F in UNLIT keys inside a lit ring; the flasher inverts that
and draws a DOWN ARROW ("into the keyboard") in LIT keys over unlit ones. A
negative-space arrow was tried first: in a 4x4 hole it read as a plus sign.
Geometry is imported from the host generator, not copied, so a change to the
mark there reaches this icon on the next run.

Written (Android vector drawables, so one file serves every density):
  res/drawable/ic_launcher_background.xml   the dark body, full bleed
  res/drawable/ic_launcher_foreground.xml   the key grid
  res/drawable/ic_launcher_monochrome.xml   lit keys only, for themed icons (API 33+)
  res/drawable/ic_stat_flash.xml            notification icon, white on transparent
  res/mipmap-anydpi/ic_launcher{,_round}.xml

    python3 android/tools/gen_launcher_icon.py              # write the drawables
    python3 android/tools/gen_launcher_icon.py --sheet X.png  # preview sheet, write nothing
"""
import argparse
import io
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(REPO / "tools"))
import gen_brand_icons as gb  # noqa: E402

RES = HERE.parent / "app" / "src" / "main" / "res"

# Lit keys (1) draw a down arrow: a two-key shaft, then a three-row head.
GRID_FLASH = [
    "001100",
    "001100",
    "001100",
    "111111",
    "011110",
    "001100",
]

# The colour variant's key sweep and body, as in gen_brand_icons.svg().
KEY_FROM, KEY_TO = "#1D4ED8", "#22D3EE"
BODY_TOP, BODY_BOTTOM = "#182135", "#080C16"

# Adaptive icons draw on a 108dp canvas, and launchers mask it to anything from a
# circle to a squircle. Only a 66dp circle is guaranteed visible. A 48dp grid puts
# its corner keys 34dp from the centre: inside every mask, at most just past the
# 33dp safe radius, and still large enough to read at launcher sizes.
CANVAS = 108.0
GRID_DP = 48.0

AAPT = 'xmlns:aapt="http://schemas.android.com/aapt"'
ANDROID = 'xmlns:android="http://schemas.android.com/apk/res/android"'


def keys(size, grid_size, offset=None):
    """(x, y, key, radius, lit) per key, mapped from gb's 1024 units to a size-unit canvas."""
    area = gb.S - 2 * gb.AREA_INSET
    scale = grid_size / area
    off = (size - grid_size) / 2 if offset is None else offset
    for _r, _c, x, y, lit in gb._keys(GRID_FLASH):
        yield (off + (x - gb.AREA_INSET) * scale, off + (y - gb.AREA_INSET) * scale,
               gb.KEY * scale, gb.KEY_R * scale, lit)


def rrect(x, y, w, r):
    s = w - 2 * r
    return (f"M{x + r:.2f},{y:.2f}h{s:.2f}a{r:.2f},{r:.2f} 0 0 1 {r:.2f},{r:.2f}"
            f"v{s:.2f}a{r:.2f},{r:.2f} 0 0 1 {-r:.2f},{r:.2f}h{-s:.2f}"
            f"a{r:.2f},{r:.2f} 0 0 1 {-r:.2f},{-r:.2f}v{-s:.2f}"
            f"a{r:.2f},{r:.2f} 0 0 1 {r:.2f},{-r:.2f}z")


def vector(size, body, dp=None):
    dp = dp or size
    return (f'<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Generated by android/tools/gen_launcher_icon.py. Do not edit. -->\n'
            f'<vector {ANDROID} {AAPT}\n'
            f'    android:width="{dp:g}dp" android:height="{dp:g}dp"\n'
            f'    android:viewportWidth="{size:g}" android:viewportHeight="{size:g}">\n'
            f'{body}</vector>\n')


def gradient_path(d, x0, y0, x1, y1, stops):
    items = "".join(f'                <item android:offset="{o}" android:color="{c}"/>\n' for o, c in stops)
    return (f'    <path android:pathData="{d}">\n'
            f'        <aapt:attr name="android:fillColor">\n'
            f'            <gradient android:type="linear" android:startX="{x0:.2f}" android:startY="{y0:.2f}"\n'
            f'                android:endX="{x1:.2f}" android:endY="{y1:.2f}">\n'
            f'{items}'
            f'            </gradient>\n'
            f'        </aapt:attr>\n'
            f'    </path>\n')


def background_xml():
    d = f"M0,0h{CANVAS:g}v{CANVAS:g}h{-CANVAS:g}z"
    return vector(CANVAS, gradient_path(d, 0, 0, 0, CANVAS, [(0, BODY_TOP), (1, BODY_BOTTOM)]))


def foreground_xml():
    ks = list(keys(CANVAS, GRID_DP))
    lit = "".join(rrect(x, y, k, r) for x, y, k, r, on in ks if on)
    ghost = "".join(rrect(x, y, k, r) for x, y, k, r, on in ks if not on)
    a0 = (CANVAS - GRID_DP) / 2
    a1 = a0 + GRID_DP
    body = f'    <path android:pathData="{ghost}" android:fillColor="#0DFFFFFF"/>\n'
    body += gradient_path(lit, a0, a0, a1, a1, [(0, KEY_FROM), (1, KEY_TO)])
    # The top-lit sheen, one gradient per key (a vector gradient is in path space).
    for x, y, k, r, on in ks:
        if on:
            body += gradient_path(rrect(x, y, k, r), 0, y, 0, y + k,
                                  [(0, "#57FFFFFF"), (0.55, "#0AFFFFFF"), (1, "#38000018")])
    return vector(CANVAS, body)


def monochrome_xml():
    lit = "".join(rrect(x, y, k, r) for x, y, k, r, on in keys(CANVAS, GRID_DP) if on)
    return vector(CANVAS, f'    <path android:pathData="{lit}" android:fillColor="#FFFFFFFF"/>\n')


def stat_xml():
    # Status-bar icons are 24dp with a 1dp margin; the system tints the alpha mask.
    lit = "".join(rrect(x, y, k, r) for x, y, k, r, on in keys(24, 22) if on)
    return vector(24, f'    <path android:pathData="{lit}" android:fillColor="#FFFFFFFF"/>\n')


ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by android/tools/gen_launcher_icon.py. Do not edit. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""


def outputs():
    return {
        RES / "drawable" / "ic_launcher_background.xml": background_xml(),
        RES / "drawable" / "ic_launcher_foreground.xml": foreground_xml(),
        RES / "drawable" / "ic_launcher_monochrome.xml": monochrome_xml(),
        RES / "drawable" / "ic_stat_flash.xml": stat_xml(),
        RES / "mipmap-anydpi" / "ic_launcher.xml": ADAPTIVE,
        RES / "mipmap-anydpi" / "ic_launcher_round.xml": ADAPTIVE,
    }


# --- preview: the same geometry as SVG, rendered under the launcher masks ---

def preview_svg(mask, themed=False):
    ks = list(keys(CANVAS, GRID_DP))
    a0 = (CANVAS - GRID_DP) / 2
    a1 = a0 + GRID_DP
    shapes = {
        "circle": '<circle cx="54" cy="54" r="36"/>',
        "squircle": '<rect x="18" y="18" width="72" height="72" rx="24"/>',
        "square": '<rect x="18" y="18" width="72" height="72" rx="6"/>',
    }
    # Built outside the list: adjacent literals inside a list read like a missing comma
    # (CodeQL py/implicit-string-concatenation-in-list).
    defs = (f'<defs><clipPath id="m">{shapes[mask]}</clipPath>'
            '<linearGradient id="b" x1="0" y1="0" x2="0" y2="1">'
            f'<stop offset="0" stop-color="{BODY_TOP}"/><stop offset="1" stop-color="{BODY_BOTTOM}"/></linearGradient>'
            f'<linearGradient id="k" gradientUnits="userSpaceOnUse" x1="{a0}" y1="{a0}" x2="{a1}" y2="{a1}">'
            f'<stop offset="0" stop-color="{KEY_FROM}"/><stop offset="1" stop-color="{KEY_TO}"/></linearGradient>'
            '<linearGradient id="c" x1="0" y1="0" x2="0" y2="1">'
            '<stop offset="0" stop-color="#FFF" stop-opacity="0.34"/>'
            '<stop offset="0.55" stop-color="#FFF" stop-opacity="0.04"/>'
            '<stop offset="1" stop-color="#000018" stop-opacity="0.22"/></linearGradient></defs>')
    ground = "#DDE7F5" if themed else "url(#b)"
    out = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72">', defs,
           '<g clip-path="url(#m)">', f'<rect width="108" height="108" fill="{ground}"/>']
    for x, y, k, r, on in ks:
        if themed:
            if on:
                out.append(f'<path d="{rrect(x, y, k, r)}" fill="#2B4A7A"/>')
        elif on:
            out.append(f'<path d="{rrect(x, y, k, r)}" fill="url(#k)"/><path d="{rrect(x, y, k, r)}" fill="url(#c)"/>')
        else:
            out.append(f'<path d="{rrect(x, y, k, r)}" fill="#FFF" fill-opacity="0.05"/>')
    out.append("</g></svg>")
    return "".join(out)


def stat_svg():
    lit = "".join(rrect(x, y, k, r) for x, y, k, r, on in keys(24, 22) if on)
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="{lit}" fill="#FFF"/></svg>'


def sheet(path):
    import cairosvg
    from PIL import Image, ImageDraw

    def png(src, px):
        return Image.open(io.BytesIO(cairosvg.svg2png(bytestring=src.encode(),
                                                      output_width=px, output_height=px))).convert("RGBA")

    tiles = []
    for mask in ("circle", "squircle", "square"):
        tiles += [png(preview_svg(mask), 192), png(preview_svg(mask), 48)]
    tiles += [png(preview_svg("circle", themed=True), 192)]
    stat_dark = Image.new("RGBA", (96, 96), "#202124")
    for px, pos in ((24, (8, 36)), (48, (40, 24))):
        stat_dark.alpha_composite(png(stat_svg(), px), pos)
    tiles.append(stat_dark)

    w = sum(t.width for t in tiles) + 16 * (len(tiles) + 1)
    img = Image.new("RGBA", (w, 232), "#F1F3F4")
    x = 16
    d = ImageDraw.Draw(img)
    labels = ["circle 192", "48", "squircle 192", "48", "square 192", "48", "themed", "status bar"]
    for t, label in zip(tiles, labels):
        img.alpha_composite(t, (x, 16 + (192 - t.height) // 2))
        d.text((x, 212), label, fill="#333")
        x += t.width + 16
    img.save(path)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--sheet", help="write a preview contact sheet to this PNG and nothing else")
    args = ap.parse_args()
    if args.sheet:
        sheet(args.sheet)
        return
    for path, text in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(path.relative_to(REPO))


if __name__ == "__main__":
    main()
