#!/usr/bin/env python3
"""
Parse the QMK firmware layers.h enum and write layer index → name mappings
to polyhost/res/layer_names.yaml.

Run from the PolyKybdHost root or from anywhere:
    python scripts/generate_layer_names.py
    python scripts/generate_layer_names.py --layers-h /path/to/layers.h
    python scripts/generate_layer_names.py --out /path/to/layer_names.yaml
"""
import argparse
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
REPO_ROOT = SCRIPT_DIR.parent

# The enum moved twice: out of the per-keymap directory when split72/split42 began
# sharing one keymap, and out of keyboards/handwired/ when the boards were promoted.
# The old default silently pointed at a path that no longer exists, so this file was
# never regenerated and drifted several layers out of date.
DEFAULT_LAYERS_H = (
    REPO_ROOT.parent / "qmk_firmware" / "keyboards" / "polykybd" / "layers.h"
)
DEFAULT_OUT = REPO_ROOT / "polyhost" / "res" / "layer_names.yaml"


def _display_source(path: Path) -> str:
    """Trim an absolute layers.h path down to its qmk_firmware-relative part."""
    parts = path.resolve().parts
    if "qmk_firmware" in parts:
        return str(Path(*parts[parts.index("qmk_firmware"):]))
    return path.name


def parse_layers_h(path: Path) -> dict[int, str]:
    text = path.read_text(encoding="utf-8")

    match = re.search(r'enum\s+kb_layers\s*\{(.*?)\};', text, re.S)
    if not match:
        raise ValueError(f"kb_layers enum not found in {path}")

    body = match.group(1)
    name_to_idx: dict[str, int] = {}
    idx_to_name: dict[int, str] = {}
    current_val = 0

    for line in body.splitlines():
        line = re.sub(r'//.*', '', line).strip().rstrip(',').strip()
        if not line:
            continue
        m = re.match(r'(\w+)(?:\s*=\s*(\S+))?', line)
        if not m:
            continue
        name = m.group(1)
        value_str = m.group(2)

        if value_str is not None:
            try:
                val = int(value_str, 0)
            except ValueError:
                # alias like _L0 = _BL
                val = name_to_idx.get(value_str, current_val)
        else:
            val = current_val

        name_to_idx[name] = val
        # Last definition for each index wins (_L0 = _BL → "L0" not "BL")
        idx_to_name[val] = name.lstrip('_')
        current_val = val + 1

    return dict(sorted(idx_to_name.items()))


def write_yaml(layer_names: dict[int, str], out: Path, layers_h: Path) -> None:
    lines = [
        f"# Auto-generated by scripts/generate_layer_names.py",
        # Repo-relative, not absolute: the previous version embedded the generating
        # machine's home directory, so regenerating on any other machine produced a
        # one-line diff that said nothing about the content.
        f"# Source: {_display_source(layers_h)}",
        f"# Run: python scripts/generate_layer_names.py",
        "",
    ]
    for idx, name in layer_names.items():
        lines.append(f"{idx}: {name}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--layers-h", type=Path, default=DEFAULT_LAYERS_H,
                        help=f"Path to layers.h (default: {DEFAULT_LAYERS_H})")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT,
                        help=f"Output YAML path (default: {DEFAULT_OUT})")
    args = parser.parse_args()

    if not args.layers_h.exists():
        print(f"Error: layers.h not found at {args.layers_h}", file=sys.stderr)
        print("Pass --layers-h to specify the correct path.", file=sys.stderr)
        sys.exit(1)

    layer_names = parse_layers_h(args.layers_h)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    write_yaml(layer_names, args.out, args.layers_h)
    print(f"Written {len(layer_names)} layers to {args.out}")
    for idx, name in layer_names.items():
        print(f"  {idx}: {name}")


if __name__ == "__main__":
    main()
