"""Golden vectors for the context codec, shared by host and firmware tests.

Writes ``tests/util/ctx_codec_vectors.json`` (host) and, with
``--firmware-header``, ``keyboards/polykybd/base/tests/ctx_codec_vectors.h``.
Each vector is a ROI box, the payload the host encoder produces and the 360-byte
overlay the firmware must decode it to. Deterministic: re-running rewrites the
same bytes, so a diff means the encoder or the table changed.

    python tools/gen_ctx_vectors.py \\
        --firmware-header ../qmk_firmware/keyboards/polykybd/base/tests/ctx_codec_vectors.h
"""
import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "tools"))

from polyhost.util import ctx_codec  # noqa: E402
from train_ctx_table import template_masks  # noqa: E402


def synthetic():
    import numpy as np
    out = []
    m = np.zeros((40, 72), bool); m[39, 71] = True
    out.append(("single pixel, bottom-right corner", m))
    m = np.zeros((40, 72), bool); m[0, 0] = True
    out.append(("single pixel, top-left corner", m))
    m = np.zeros((40, 72), bool); m[10:20, 30:40] = True
    out.append(("solid 10x10 block", m))
    m = np.zeros((40, 72), bool)
    for y in range(8):
        for x in range(8):
            m[16 + y, 60 + x] = (x + y) % 2 == 0
    out.append(("8x8 checkerboard", m))
    return out


def vectors():
    import numpy as np
    masks = sorted(template_masks(), key=lambda m: np.packbits(m).tobytes())
    picks = [("template cell %d" % i, masks[i]) for i in (0, len(masks) // 3, 2 * len(masks) // 3)]
    largest = max(range(len(masks)), key=lambda i: len(ctx_codec.encode(ctx_codec.crop_to_roi(masks[i]))))
    picks.append(("template cell %d (largest payload)" % largest, masks[largest]))
    out = []
    for i, (name, m) in enumerate(synthetic() + picks):
        rows, cols = np.any(m, axis=1), np.any(m, axis=0)
        top, bottom = [int(v) for v in np.where(rows)[0][[0, -1]]]
        left, right = [int(v) for v in np.where(cols)[0][[0, -1]]]
        roi = m[top:bottom + 1, left:right + 1]
        payload = ctx_codec.encode(roi)
        assert (ctx_codec.decode(payload, *roi.shape) == roi).all(), name
        # The same image as a cmd 41 record (keycode KC_A+i, modifier 3i mod 16, so all four bits vary), when
        # it fits the length field; pins the header packing on both sides.
        record = b""
        if len(payload) <= ctx_codec.MAX_RECORD_PAYLOAD:
            record = ctx_codec.pack_record(4 + i, (3 * i) % 16, top, left, roi.shape[0], roi.shape[1], payload)
        out.append({"name": name, "top": top, "left": left,
                    "height": int(roi.shape[0]), "width": int(roi.shape[1]),
                    "payload": payload.hex(), "overlay": np.packbits(m).tobytes().hex(),
                    "keycode": 4 + i, "modifier": (3 * i) % 16, "record": record.hex()})
    return out


def c_bytes(hexstr):
    b = bytes.fromhex(hexstr)
    return ", ".join(f"0x{x:02x}" for x in b) if b else "0"


def header(vecs):
    lines = ["// SPDX-License-Identifier: GPL-2.0-or-later",
             "// GENERATED by PolyKybdHost tools/gen_ctx_vectors.py -- do not edit.",
             "// Golden vectors: what the host encoder produced, and the overlay the",
             f"// decoder must produce from it (table v{ctx_codec.TABLE_ID}).",
             "#pragma once", "", "#include <stdint.h>", "",
             "typedef struct {", "    const char *name;", "    uint8_t top, left, height, width;",
             "    uint8_t len;", "    const uint8_t *payload;", "    const uint8_t *overlay;",
             "    uint8_t keycode, modifier;", "    uint8_t record_len;  // 0: payload too long for a record",
             "    const uint8_t *record;",
             "} ctx_vector_t;", ""]
    for i, v in enumerate(vecs):
        lines.append(f"static const uint8_t ctx_vec{i}_payload[] = {{{c_bytes(v['payload'])}}};")
        lines.append(f"static const uint8_t ctx_vec{i}_overlay[360] = {{{c_bytes(v['overlay'])}}};")
        lines.append(f"static const uint8_t ctx_vec{i}_record[] = {{{c_bytes(v['record'])}}};")
    lines += ["", "static const ctx_vector_t ctx_vectors[] = {"]
    for i, v in enumerate(vecs):
        n = len(bytes.fromhex(v["payload"]))
        r = len(bytes.fromhex(v["record"]))
        lines.append(f'    {{"{v["name"]}", {v["top"]}, {v["left"]}, {v["height"]}, {v["width"]}, '
                     f'{n}, ctx_vec{i}_payload, ctx_vec{i}_overlay, '
                     f'{v["keycode"]}, {v["modifier"]}, {r}, ctx_vec{i}_record}},')
    lines += ["};", ""]
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--firmware-header")
    args = ap.parse_args(argv)
    vecs = vectors()
    out = os.path.join(ROOT, "tests", "util", "ctx_codec_vectors.json")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        json.dump({"table_id": ctx_codec.TABLE_ID, "vectors": vecs}, fh, indent=1)
        fh.write("\n")
    print(f"{out}: {len(vecs)} vectors")
    if args.firmware_header:
        with open(args.firmware_header, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(header(vecs))
        print(f"{args.firmware_header}: written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
