"""Train the context-coding probability table (HID cmd 41) from the templates.

Writes ``polyhost/res/ctx_table_v<N>.bin`` (1024 bytes) and, with
``--firmware-header``, the matching ``keyboards/polykybd/base/ctx_table.h``.
Both are generated from the same bytes, so the host encoder and the firmware
decoder cannot disagree.

    python tools/train_ctx_table.py --table-id 1 \\
        --firmware-header ../qmk_firmware/keyboards/polykybd/base/ctx_table.h

⚠️ A table that has shipped is FROZEN. Retraining means a new ``--table-id``
(and a firmware that knows it), never overwriting an existing id: a keyboard
decoding with a different table than the host encoded with draws garbage and
nothing reports an error. The tool refuses to overwrite an existing table file
unless ``--force`` is given, which is only for a table that never shipped.

Training input: every distinct non-empty 72x40 cell of every template PNG in
``polyhost/res/overlays`` (all modifier layers). The result is deterministic.
"""
import argparse
import glob
import hashlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from polyhost.device.device_settings import DeviceSettings  # noqa: E402
from polyhost.device.im_converter import ImageConverter  # noqa: E402
from polyhost.device.keys import Modifier  # noqa: E402
from polyhost.util import ctx_codec  # noqa: E402


def template_masks():
    import numpy as np
    seen = {}
    for path in sorted(glob.glob(os.path.join(ROOT, "polyhost", "res", "overlays", "*.png"))):
        conv = ImageConverter(DeviceSettings())
        if not conv.open(path):
            raise SystemExit(f"cannot read {path}")
        for mod in Modifier:
            for ov in (conv.extract_overlays(mod) or {}).values():
                seen.setdefault(ov.all_bytes, None)
    masks = [np.unpackbits(np.frombuffer(b, dtype=np.uint8)).reshape(40, 72).astype(bool)
             for b in sorted(seen)]
    return masks


def header(table: bytes, table_id: int, n_masks: int) -> str:
    digest = hashlib.sha256(table).hexdigest()
    rows = [", ".join(f"{b:3d}" for b in table[i:i + 16]) for i in range(0, len(table), 16)]
    body = ",\n    ".join(rows)
    return f"""// SPDX-License-Identifier: GPL-2.0-or-later
// GENERATED by PolyKybdHost tools/train_ctx_table.py -- do not edit.
//
// Context-coding probability table v{table_id} (HID cmd 41): P(pixel is 0) * 256
// for each of the 1024 neighbour contexts, trained on {n_masks} distinct template
// cells. Byte-identical to PolyKybdHost polyhost/res/ctx_table_v{table_id}.bin
// (sha256 {digest}).
//
// FROZEN once shipped: a retrained table is a new id, never an edit to this one.
#pragma once

#include <stdint.h>

#define CTX_TABLE_ID {table_id}
#define CTX_TABLE_SHA256 "{digest}"

static const uint8_t ctx_table_v{table_id}[1024] = {{
    {body}
}};
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--table-id", type=int, required=True)
    ap.add_argument("--firmware-header", help="also write the firmware ctx_table.h here")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing table file (only for a table that never shipped)")
    args = ap.parse_args(argv)

    out = os.path.join(ROOT, "polyhost", "res", f"ctx_table_v{args.table_id}.bin")
    masks = template_masks()
    table = ctx_codec.train(masks)
    if os.path.exists(out) and not args.force:
        with open(out, "rb") as fh:
            if fh.read() != table:
                raise SystemExit(f"{out} exists with different contents; tables are frozen "
                                 "(use a new --table-id, or --force if it never shipped)")
    with open(out, "wb") as fh:
        fh.write(table)
    print(f"{out}: {len(table)} bytes from {len(masks)} cells, sha256 {hashlib.sha256(table).hexdigest()}")
    if args.firmware_header:
        with open(args.firmware_header, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(header(table, args.table_id, len(masks)))
        print(f"{args.firmware_header}: written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
