from enum import Enum


class HidId(Enum):
    ID_GET_PROTOCOL_VERSION = 1
    ID_GET_KEYBOARD_VALUE = 2
    ID_SET_KEYBOARD_VALUE = 3
    ID_DYNAMIC_KEYMAP_GET_KEYCODE = 4
    ID_DYNAMIC_KEYMAP_SET_KEYCODE = 5
    ID_DYNAMIC_KEYMAP_RESET = 6
    ID_CUSTOM_SET_VALUE = 7
    ID_CUSTOM_GET_VALUE = 8
    ID_CUSTOM_SAVE = 9
    ID_EEPROM_RESET = 10
    ID_BOOTLOADER_JUMP = 11
    ID_DYNAMIC_KEYMAP_MACRO_GET_COUNT = 12
    ID_DYNAMIC_KEYMAP_MACRO_GET_BUFFER_SIZE = 13
    ID_DYNAMIC_KEYMAP_MACRO_GET_BUFFER = 14
    ID_DYNAMIC_KEYMAP_MACRO_SET_BUFFER = 15
    ID_DYNAMIC_KEYMAP_MACRO_RESET = 16
    ID_DYNAMIC_KEYMAP_GET_LAYER_COUNT = 17
    ID_DYNAMIC_KEYMAP_GET_BUFFER = 18
    ID_DYNAMIC_KEYMAP_SET_BUFFER = 19
    ID_DYNAMIC_KEYMAP_GET_ENCODER = 20
    ID_DYNAMIC_KEYMAP_SET_ENCODER = 21


class Cmd(Enum):
    GET_ID = 6
    GET_LANG = 7
    GET_LANG_LIST = 8
    CHANGE_LANG = 9
    SEND_OVERLAY = 10
    OVERLAY_FLAGS_ON = 11
    OVERLAY_FLAGS_OFF = 12
    SET_BRIGHTNESS = 13
    KEYPRESS = 14
    IDLE_STATE = 15
    START_COMPRESSED_OVERLAY = 16
    SEND_COMPRESSED_OVERLAY = 17
    START_ROI_OVERLAY = 18
    SEND_ROI_OVERLAY = 19
    SET_UNICODE_MODE = 20
    SEND_OVERLAY_MAPPING = 21
